url: "https://annapkwossek.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Anna Kwossek" # the name of your site, e.g. ACME Corp.
description: "Anna Kwossek's personal webpage"
