menu:
- {name: 'publications', url: '/publications'}
- {name: 'teaching', url: '/teaching'}
- {name: 'miscellaneous', url: '/miscellaneous'}
- {name: 'contact', url: '/contact'}

social:
- {icon: 'linkedin', link: 'http://linkedin.com/in/anna-paula-kwossek-30abb2228'}

contacts:
- {name: 'Anna Kwossek', institution: 'University of Vienna', institution_address: 'Kolingasse 14-16, AT-Vienna', phone: '+43-1-4277-38692', email: 'anna.paula.kwossek@univie.ac.at', office: '05.51'}
